# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a43cf88d37fb8407dd606dcf16b2897dbea501e6eb73c2f369190612dfadabcda8689bc8bea77bd12a24c6a171e31cd912219591745b0b222860ccf7726139

test:
  secret_key_base: 90a30bb159a1f61b488bd15bc9d9fde3607a317690e1cf440c67709ad3828fced78c65401fccc9659753c9932024c1663836d71ec609c5462a7da06f3035ef07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
